build: pass -DGWEATHER_COMPILATION to gir compiler
Fixes cross compilation of gir.

[20/23] Generating GWeather-3.0.gir with a custom command.
FAILED: libgweather/GWeather-3.0.gir
/usr/aarch64-linux-gnu/usr/bin/g-ir-scanner -pthread -I/usr/aarch64-linux-gnu/usr/include/gobject-introspection-1.0 -I/usr/aarch64-linux-gnu/usr/include/glib-2.0 -I/usr/aarch64-linux-gnu/usr/lib/glib-2.0/include --no-libtool --namespace=GWeather --nsversion=3.0 --warn-all --output libgweather/GWeather-3.0.gir --c-include=libgweather/gweather.h --warn-all -I/builddir/libgweather-3.28.2/libgweather -I/builddir/libgweather-3.28.2/build/libgweather -I./. -I../. --filelist=/builddir/libgweather-3.28.2/build/libgweather/a0aebfc@@gweather-3@sha/GWeather_3.0_gir_filelist --include=GObject-2.0 --include=Gtk-3.0 --symbol-prefix=gweather --identifier-prefix=GWeather --pkg-export=gweather-3.0 --cflags-begin -I./. -I../. -I/usr/aarch64-linux-gnu/usr/include/gtk-3.0 -I/usr/aarch64-linux-gnu/usr/include/at-spi2-atk/2.0 -I/usr/aarch64-linux-gnu/usr/include/at-spi-2.0 -I/usr/aarch64-linux-gnu/usr/include/dbus-1.0 -I/usr/aarch64-linux-gnu/usr/lib/dbus-1.0/include -I/usr/aarch64-linux-gnu/usr/include/gio-unix-2.0/ -I/usr/aarch64-linux-gnu/usr/include/cairo -I/usr/aarch64-linux-gnu/usr/include/libdrm -I/usr/aarch64-linux-gnu/usr/include/pango-1.0 -I/usr/aarch64-linux-gnu/usr/include/harfbuzz -I/usr/aarch64-linux-gnu/usr/include/fribidi -I/usr/aarch64-linux-gnu/usr/include/atk-1.0 -I/usr/aarch64-linux-gnu/usr/include/pixman-1 -I/usr/aarch64-linux-gnu/usr/include/freetype2 -I/usr/aarch64-linux-gnu/usr/include/libpng16 -I/usr/aarch64-linux-gnu/usr/include/gdk-pixbuf-2.0 -I/usr/aarch64-linux-gnu/usr/include/libmount -I/usr/aarch64-linux-gnu/usr/include/blkid -I/usr/aarch64-linux-gnu/usr/include/uuid -I/usr/aarch64-linux-gnu/usr/include/glib-2.0 -I/usr/aarch64-linux-gnu/usr/lib/glib-2.0/include -I/usr/aarch64-linux-gnu/usr/include/libsoup-2.4 -I/usr/aarch64-linux-gnu/usr/include/libxml2 -I/usr/aarch64-linux-gnu/usr/include/geocode-glib-1.0 -D_FORTIFY_SOURCE=2 -I/usr/aarch64-linux-gnu/usr/include --cflags-end --library gweather-3 -L/builddir/libgweather-3.28.2/build/libgweather -L/usr/aarch64-linux-gnu/usr/lib --extra-library=m --extra-library=gtk-3 --extra-library=gdk-3 --extra-library=pangocairo-1.0 --extra-library=pango-1.0 --extra-library=atk-1.0 --extra-library=cairo-gobject --extra-library=cairo --extra-library=gdk_pixbuf-2.0 --extra-library=gio-2.0 --extra-library=gobject-2.0 --extra-library=glib-2.0 --extra-library=soup-2.4 --extra-library=xml2 --extra-library=geocode-glib
In file included from /builddir/libgweather-3.28.2/build/g-ir-cpp-wmkyat6f.c:4:
/builddir/libgweather-3.28.2/build/libgweather/gweather-enum-types.h:8:2: error: #error "gweather-enum-types.h must not be included individually, include gweather.h instead"
 #error "gweather-enum-types.h must not be included individually, include gweather.h instead"
  ^~~~~
In file included from /usr/aarch64-linux-gnu/usr/include/bits/libc-header-start.h:33,
                 from /usr/aarch64-linux-gnu/usr/include/limits.h:26,
                 from /usr/lib/gcc/aarch64-linux-gnu/8.2.0/include-fixed/limits.h:194,
                 from /usr/lib/gcc/aarch64-linux-gnu/8.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/aarch64-linux-gnu/8.2.0/include-fixed/limits.h:34,
                 from /usr/aarch64-linux-gnu/usr/lib/glib-2.0/include/glibconfig.h:11,
                 from /usr/aarch64-linux-gnu/usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/aarch64-linux-gnu/usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/aarch64-linux-gnu/usr/include/glib-2.0/glib.h:30,
                 from /usr/aarch64-linux-gnu/usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/aarch64-linux-gnu/usr/include/glib-2.0/glib-object.h:23,
                 from /builddir/libgweather-3.28.2/build/libgweather/gweather-enum-types.h:11,
                 from /builddir/libgweather-3.28.2/build/g-ir-cpp-wmkyat6f.c:4:
/usr/aarch64-linux-gnu/usr/include/features.h:381:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
In file included from /builddir/libgweather-3.28.2/build/libgweather/gweather-enum-types.h:12,
                 from /builddir/libgweather-3.28.2/build/g-ir-cpp-wmkyat6f.c:4:
./libgweather/gweather-version.h:28:2: error: #error "gweather-version.h must not be included individually, include gweather.h instead"
 #error "gweather-version.h must not be included individually, include gweather.h instead"
  ^~~~~
In file included from /builddir/libgweather-3.28.2/build/g-ir-cpp-wmkyat6f.c:5:
/builddir/libgweather-3.28.2/libgweather/gweather.h:25:2: error: #error "libgweather should only be used if you understand that it's subject to change, and is not supported as a fixed API/ABI or as part of the platform"
 #error "libgweather should only be used if you understand that it's subject to change, and is not supported as a fixed API/ABI or as part of the platform"
  ^~~~~
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 107, in preprocess
    self.spawn(pp_args)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'aarch64-linux-gnu-cpp' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner.wrapped", line 106, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 555, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 459, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 307, in _parse
    self._cpp_options)
  File "/usr/lib/gobject-introspection/giscanner/ccompiler.py", line 211, in preprocess
    extra_postargs=extra_postargs)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 109, in preprocess
    raise CompileError(msg)
distutils.errors.CompileError: command 'aarch64-linux-gnu-cpp' failed with exit status 1
ninja: build stopped: subcommand failed.